complete -c cargo -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_use_subcommand" -f -a "crev"
complete -c cargo -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from crev" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from crev" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "config" -d 'Local configuration'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "crate" -d 'Crate related operations (review, verify...)'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "id" -d 'Id (own and of other users)'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "proof" -d 'Find a proof in the proof repo'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "repo" -d 'Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "trust" -d 'Add a Trust proof by an Id or a URL'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "goto" -d 'Shortcut for `crate goto`'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "open" -d 'Shortcut for `crate open`'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "publish" -d 'Shortcut for `repo publish`'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "review" -d 'Shortcut for `crate review`'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "update" -d 'Shortcut for `repo update`'
complete -c cargo -n "__fish_seen_subcommand_from crev" -f -a "verify" -d 'Shortcut for `crate verify`'
complete -c cargo -n "__fish_seen_subcommand_from config" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from config" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from config" -f -a "edit" -d 'Edit the config file'
complete -c cargo -n "__fish_seen_subcommand_from config" -f -a "completions" -d 'Completions'
complete -c cargo -n "__fish_seen_subcommand_from config" -f -a "dir" -d 'Print the dir containing config files'
complete -c cargo -n "__fish_seen_subcommand_from config" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from completions" -l shell
complete -c cargo -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from crate" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from crate" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "goto" -d 'Start a shell in source directory of a crate under review'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "open" -d 'Open the source code of a crate'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "clean" -d 'Clean the source code directory of a crate (eg. after review)'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "diff" -d 'Diff between two versions of a package'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "dir" -d 'Display the path of the source code directory of a crate'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "verify" -d 'Verify dependencies'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "mvp" -d 'Most valuable players (reviewers)'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "review" -d 'Review a crate (code review, security advisory, flag issues)'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "unreview" -d 'Unreview (overwrite with an null review)'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "search" -d 'Search crates on crates.io sorting by review count'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "info" -d 'Display rich info about the given crate'
complete -c cargo -n "__fish_seen_subcommand_from crate" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from goto" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from open" -l cmd -d 'Shell command to execute with crate directory as an argument. Eg. "code --wait -n" for VSCode'
complete -c cargo -n "__fish_seen_subcommand_from open" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from open" -l cmd-save -d 'Save the `--cmd` argument to be used a default in the future'
complete -c cargo -n "__fish_seen_subcommand_from open" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from open" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from open" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from clean" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from clean" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from clean" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from clean" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l src -d 'Source version - defaults to the last reviewed one'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l dst -d 'Destination version - defaults to the current one'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l redundancy -d 'Number of reviews required'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l understanding -d 'Required understanding'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l thoroughness -d 'Required thoroughness'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from diff" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from diff" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from diff" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from dir" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l redundancy -d 'Number of reviews required'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l understanding -d 'Required understanding'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l thoroughness -d 'Required thoroughness'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l for-id -d 'Root identity to calculate the Web of Trust for [default: current user id]'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-digest -d 'Show crate content digest'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-leftpad-index -d 'Show crate leftpad index (recent downloads / loc)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-downloads -d 'Show crate download counts'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-owners -d 'Show crate owners counts'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-latest-trusted -d 'Show latest trusted version'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-reviews -d 'Show reviews count'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-loc -d 'Show Lines of Code'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-issues -d 'Show count of issues reported'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-geiger -d 'Show geiger (unsafe lines) count'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-flags -d 'Show crate flags'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from verify" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-all -d 'Show all'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s i -l interactive
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-verified -d 'Display only crates not passing the verification'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-known-owners -d 'Skip crate from known owners (use `edit known` to edit the list)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-indirect -d 'Skip dependencies that are not direct'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l recursive -d 'Calculate recursive metrics for your packages'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l redundancy -d 'Number of reviews required'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l understanding -d 'Required understanding'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l thoroughness -d 'Required thoroughness'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l for-id -d 'Root identity to calculate the Web of Trust for [default: current user id]'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from mvp" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from review" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from review" -l affected -d 'This release contains advisory (important fix)'
complete -c cargo -n "__fish_seen_subcommand_from review" -l severity -d 'Severity of bug/security issue [none low medium high]'
complete -c cargo -n "__fish_seen_subcommand_from review" -l diff
complete -c cargo -n "__fish_seen_subcommand_from review" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from review" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from review" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from review" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from review" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from review" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from review" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from review" -l advisory -d 'Create advisory urging to upgrade to a safe version'
complete -c cargo -n "__fish_seen_subcommand_from review" -l issue -d 'Flag the crate as buggy/low-quality/dangerous'
complete -c cargo -n "__fish_seen_subcommand_from review" -l skip-activity-check
complete -c cargo -n "__fish_seen_subcommand_from review" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from review" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from review" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l affected -d 'This release contains advisory (important fix)'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l severity -d 'Severity of bug/security issue [none low medium high]'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l diff
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l advisory -d 'Create advisory urging to upgrade to a safe version'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l issue -d 'Flag the crate as buggy/low-quality/dangerous'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l skip-activity-check
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from unreview" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from search" -l count -d 'Number of results'
complete -c cargo -n "__fish_seen_subcommand_from search" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from search" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from info" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from info" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from info" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from info" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from info" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from info" -l redundancy -d 'Number of reviews required'
complete -c cargo -n "__fish_seen_subcommand_from info" -l understanding -d 'Required understanding'
complete -c cargo -n "__fish_seen_subcommand_from info" -l thoroughness -d 'Required thoroughness'
complete -c cargo -n "__fish_seen_subcommand_from info" -l for-id -d 'Root identity to calculate the Web of Trust for [default: current user id]'
complete -c cargo -n "__fish_seen_subcommand_from info" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from info" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from info" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from info" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from info" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from info" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from info" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from info" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from info" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from info" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from info" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from id" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from id" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "new" -d 'Create a new Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "export" -d 'Export your own Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "import" -d 'Import an Id as your own'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "current" -d 'Show your current Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "switch" -d 'Change current Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "passwd" -d 'Change passphrase'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "set-url" -d 'Change repo URL for the current Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "trust" -d 'Trust an Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "untrust" -d 'Untrust (remove) trust'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "distrust" -d 'Distrust an Id'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "query" -d 'Query Ids'
complete -c cargo -n "__fish_seen_subcommand_from id" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from new" -l url -d 'URL of a git repository to be associated with the new Id'
complete -c cargo -n "__fish_seen_subcommand_from new" -l github-username -d 'Github username (instead of --url)'
complete -c cargo -n "__fish_seen_subcommand_from new" -l https-push -d 'Setup `https` instead of recommended `ssh`-based push url'
complete -c cargo -n "__fish_seen_subcommand_from new" -l no-url -d 'Create an identity without ability to publish anything'
complete -c cargo -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from export" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from export" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from import" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from import" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from current" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from current" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from switch" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from switch" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from passwd" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from passwd" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from set-url" -l https-push -d 'Setup `https` instead of recommended `ssh`-based push url'
complete -c cargo -n "__fish_seen_subcommand_from set-url" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from set-url" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l level -d 'Shortcut for setting trust level without editing'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from trust" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from trust" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -l level -d 'Shortcut for setting trust level without editing'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from untrust" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -l level -d 'Shortcut for setting trust level without editing'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from distrust" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from query" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from query" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "current" -d 'Show current Id'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "all" -d 'Show all known Ids'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "own" -d 'Show own Ids'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "trusted" -d 'List trusted ids'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from current" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from current" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from current" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from current" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from current" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from current" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from all" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from all" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from all" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from all" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from all" -l for-id
complete -c cargo -n "__fish_seen_subcommand_from all" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from all" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from own" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from own" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from own" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from own" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from own" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from own" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l for-id
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from proof" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from proof" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from proof" -f -a "find" -d 'Find a proof'
complete -c cargo -n "__fish_seen_subcommand_from proof" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from find" -l crate
complete -c cargo -n "__fish_seen_subcommand_from find" -l vers
complete -c cargo -n "__fish_seen_subcommand_from find" -l author -d 'Find a proof by a crev Id'
complete -c cargo -n "__fish_seen_subcommand_from find" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from find" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from repo" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from repo" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "publish" -d 'Publish to remote repository'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "update" -d 'Update data from online sources (proof repositories, crates.io)'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "git" -d 'Run raw git commands in the local proof repository'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "edit" -d 'Edit README.md of the current Id, ...'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "import" -d 'Import proofs'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "query" -d 'Query proofs'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "fetch" -d 'Fetch proofs from external sources'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "dir" -d 'Print the dir containing local copy of the proof repository'
complete -c cargo -n "__fish_seen_subcommand_from repo" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from publish" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from publish" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from update" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from update" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from update" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from update" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from update" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from update" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from update" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from update" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from update" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from git" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from git" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from edit" -f -a "readme" -d 'Edit your README.md file'
complete -c cargo -n "__fish_seen_subcommand_from edit" -f -a "known" -d 'Edit your KNOWN_CRATE_OWNERS.md file'
complete -c cargo -n "__fish_seen_subcommand_from edit" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from readme" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from readme" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from known" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from known" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from import" -l reset-date -d 'Reset proof date to current date'
complete -c cargo -n "__fish_seen_subcommand_from import" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from import" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from import" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from import" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from import" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from import" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from query" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from query" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "review" -d 'Query reviews'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "advisory" -d 'Query applicable advisories'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "issue" -d 'Query applicable issues'
complete -c cargo -n "__fish_seen_subcommand_from query" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from review" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from review" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from review" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from review" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from advisory" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from advisory" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from advisory" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from advisory" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from issue" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from issue" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from issue" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from issue" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from issue" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from issue" -l trust -d 'Minimum trust level of the reviewers for reviews'
complete -c cargo -n "__fish_seen_subcommand_from issue" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from issue" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from issue" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -f -a "trusted" -d 'Fetch updates from trusted Ids'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -f -a "url" -d 'Fetch from a single public proof repository'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -f -a "all" -d 'Fetch all previously retrieved public proof repositories'
complete -c cargo -n "__fish_seen_subcommand_from fetch" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -l for-id
complete -c cargo -n "__fish_seen_subcommand_from trusted" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from trusted" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from url" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from url" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from all" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from all" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from dir" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l level -d 'Shortcut for setting trust level without editing'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from trust" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from trust" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from trust" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from goto" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from goto" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from open" -l cmd -d 'Shell command to execute with crate directory as an argument. Eg. "code --wait -n" for VSCode'
complete -c cargo -n "__fish_seen_subcommand_from open" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from open" -l cmd-save -d 'Save the `--cmd` argument to be used a default in the future'
complete -c cargo -n "__fish_seen_subcommand_from open" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from open" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from open" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from publish" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from publish" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from review" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from review" -l affected -d 'This release contains advisory (important fix)'
complete -c cargo -n "__fish_seen_subcommand_from review" -l severity -d 'Severity of bug/security issue [none low medium high]'
complete -c cargo -n "__fish_seen_subcommand_from review" -l diff
complete -c cargo -n "__fish_seen_subcommand_from review" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from review" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from review" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from review" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from review" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-commit -d 'Don\'t auto-commit local Proof Repository'
complete -c cargo -n "__fish_seen_subcommand_from review" -l print-unsigned -d 'Print unsigned proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from review" -l print-signed -d 'Print signed proof content on stdout'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-store -d 'Don\'t store the proof'
complete -c cargo -n "__fish_seen_subcommand_from review" -l advisory -d 'Create advisory urging to upgrade to a safe version'
complete -c cargo -n "__fish_seen_subcommand_from review" -l issue -d 'Flag the crate as buggy/low-quality/dangerous'
complete -c cargo -n "__fish_seen_subcommand_from review" -l skip-activity-check
complete -c cargo -n "__fish_seen_subcommand_from review" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from review" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from review" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from review" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from update" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from update" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from update" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from update" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from update" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from update" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from update" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from update" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from update" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l depth -d '[trust-graph-traversal] Maximum allowed distance from the root identity when traversing trust graph'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l high-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of high trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l medium-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of medium trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l low-cost -d '[trust-graph-traversal] Cost of traversing trust graph edge of low trust level'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l trust -d 'Minimum trust level required'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l redundancy -d 'Number of reviews required'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l understanding -d 'Required understanding'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l thoroughness -d 'Required thoroughness'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l for-id -d 'Root identity to calculate the Web of Trust for [default: current user id]'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l features -d '[cargo] Space-separated list of features to activate'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l manifest-path -d '[cargo] Path to Cargo.toml'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s Z -l unstable-flags -d '[cargo] Unstable (nightly-only) flags to Cargo'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l target -d '[cargo] Skip targets other than specified (no value = autodetect)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-digest -d 'Show crate content digest'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-leftpad-index -d 'Show crate leftpad index (recent downloads / loc)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-downloads -d 'Show crate download counts'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-owners -d 'Show crate owners counts'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-latest-trusted -d 'Show latest trusted version'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-reviews -d 'Show reviews count'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-loc -d 'Show Lines of Code'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-issues -d 'Show count of issues reported'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-geiger -d 'Show geiger (unsafe lines) count'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-flags -d 'Show crate flags'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s v -l vers
complete -c cargo -n "__fish_seen_subcommand_from verify" -l all-features -d '[cargo] Activate all available features'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l no-default-features -d '[cargo] Do not activate the `default` feature'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l no-dev-dependencies -d '[cargo] Skip dev dependencies'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l show-all -d 'Show all'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s i -l interactive
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-verified -d 'Display only crates not passing the verification'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-known-owners -d 'Skip crate from known owners (use `edit known` to edit the list)'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l skip-indirect -d 'Skip dependencies that are not direct'
complete -c cargo -n "__fish_seen_subcommand_from verify" -l recursive -d 'Calculate recursive metrics for your packages'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s u -l unrelated -d 'This crate is not neccesarily a dependency of the current cargo project'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from verify" -s V -l version -d 'Prints version information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c cargo -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
